name: Build .NET Libraries on Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/System/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        solution: [
          'src/System/System.sln',
        ]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Check for changes in solution
      id: check_changes
      run: |
        echo "Checking for changes in solution: ${{ matrix.solution }}"

        # Получаем список изменённых файлов в PR
        changed_files=$(git diff --name-only origin/develop...HEAD)
        echo "Changed files: $changed_files"
        
        # Получаем директорию, которая соответствует текущему решению из матрицы
        solution_dir=$(dirname ${{ matrix.solution }})
        
        # Проверяем, если изменения затрагивают эту директорию
        if echo "$changed_files" | grep -q "^$solution_dir/"; then
          echo "Changes detected in solution: ${{ matrix.solution }}"
          echo "solution_changed=true" >> $GITHUB_ENV
        else
          echo "No changes detected in solution: ${{ matrix.solution }}"
          echo "solution_changed=false" >> $GITHUB_ENV
        fi

    - name: Restore dependencies
      if: env.solution_changed == 'true'
      run: dotnet restore ${{ matrix.solution }}

    - name: Build solution
      if: env.solution_changed == 'true'
      run: dotnet build ${{ matrix.solution }} --configuration Release